### ISSUE TITLE
Testing env

### ISSUE THREAD

**Issue by TrySound** [Kflash/karma-rollup-plugin#1]
My office still use node0.12. I'm trying to force upgrade but it's not so fast. Also until rollup itself supports 0.12 any plugins and adapters should follow the same. Usually our travis conf looks like this

``` js
# sudo is not required since jan 2015
language: node_js
node_js:
  - "0.12"
  - "4"
  - "6"
env:
  global:
    - BUILD_TIMEOUT=10000
# node_js env knows what to do
# install: npm install
# script: npm run ci
```

**Comment by ghost** [comment]
I will look into this. First I need to push a quick fix here.

**Comment by ghost** [comment]
@TrySound Travis 0.12 is now supported. Close this?

**Comment by TrySound** [comment]
Add badge please

```
[![Build Status](https://travis-ci.org/Kflash/karma-rollup-plugin.svg)](https://travis-ci.org/Kflash/karma-rollup-plugin)
```

**Comment by TrySound** [comment]
Oops. It's added :)

**Comment by TrySound** [comment]
Thanks
