### ISSUE TITLE
2 latest versions doesn't work - code issues

### ISSUE THREAD

**Issue by ghost** [Kflash/karma-rollup-plugin#11]
@TrySound I have to revert some of your source fixes because something weird happen. It doesn't work anymore. `SyntaxError: Unexpected token ')'` Seems like Rollup isn't invoked?

Actually no time for this atm, but I have no choices rather then fix this :(

**Comment by ghost** [comment]
@TrySound To start with it didn't load the preprocessor at all when installed from NPM. When I fixed it so it loaded, I got this issue:

``` js
11 07 2016 08:37:12.660:WARN [preprocess]: Can not load "rollup"!
  TypeError: logger.create is not a function
```

And after fixing that issue, I got this issue

``` js
PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  SyntaxError: Unexpected token ')'
× Error while running the tests! Exit code: 1
```

The plugin works again now, but hasn't worked with your 2 latest contributions.

Here is a few of the issues I found
- `package.json` pointed to dist folder. But that folder doesn't exist if you use `NPM`. Added build to `prepublish` now. And removed `dist` from `.gitignore` file. Maybe not needed to remove it from there I guess.
- Important code was removed from the `$inject` function. Added it back, and moved it down. Got issues with it on `nodeJS v.6.30`
- a few other things.

TODO! Need to lint the source code again.

**Comment by TrySound** [comment]
I think you published old verion or something like this. I fixed `Unexpected token ')'` by adding `SOURCEMAPPING_URL` variable

**Comment by TrySound** [comment]
Didn't know args are so necessary. Was confused with angular like injections. Stupid arch.

**Comment by ghost** [comment]
I got  Unexpected token ')'  because the preprocessor wasn't loaded at all
with npm. After it launched i got this error because rollup wasn't found
and couldn't transpile ES6 code...

I didn't check or test sourcemap. Probably an issue there too it seems.

It now works for npm install. I used some old code to find the issues.
Maybe I forgot to change it again.

Regarding angular I think we will face more issues... but this is related
to Rollup core.

See my latest reply on the other issue.

I'm not home atm.

**Comment by jlmakes** [comment]
I'm still running into this error using `v0.2.4`,

The error messages are the same if there is no preprocessor, suggesting to me that the rollup preprocessor (let alone the bublé plugin) isn't running; all the ES6 syntax is gibberish.
