### ISSUE TITLE
touchParents and changedParents

### ISSUE THREAD

**Issue by ghost** [Kflash/karma-rollup-plugin#14]
@TrySound You know the interal Rollup source code better then I do, so can you look into this?

Look at this source code to get an idea: 
https://github.com/webpack/karma-webpack/blob/master/index.js

This is interesting:

https://github.com/webpack/karma-webpack/blob/master/index.js#L106-L115

**Comment by TrySound** [comment]
Seems like constructor and factory inject impicitly. And plugin have an access to emmiter. Maybe factory can inject it too. Let's try.

**Comment by ghost** [comment]
I did look at various preprocessor source codes now, and both Webpack and Browserify uses an emmiter. However Browserify also create a framework plugin.
https://github.com/nikku/karma-browserify/blob/master/lib/bro.js#L366-L367

The emmiter code for browserify: https://github.com/nikku/karma-browserify/blob/master/lib/bro.js#L366-L367

**Comment by brianmhunt** [comment]
Looks like an emitter /plugin would be a viable (and canonical) path.  The touch/denounce was just a hack to make it kinda work. 😀

**Comment by ghost** [comment]
Well. I try to think of a good solution, and - @TrySound - if rollup.watch() is stable enough. Could it be used to watch the source files, send a boolean flag back to a bundle function and do a re-trigger if any changes?  If that make sense...

Browserify uses watchify.

**Comment by TrySound** [comment]
It can, but is there a way to prevent karma watching?

**Comment by ghost** [comment]
I'm not sure. Actually I doubt it. Webpack solution with emmiter, tried it?

**Comment by TrySound** [comment]
Yep. But maybe without plugin class

**Comment by ghost** [comment]
It's a tricky one. I still looking at other preprocessors

**Comment by ghost** [comment]
@TrySound It didn't work? I may think we would need a framework plugin as well. As seen in browserify. And also here: https://github.com/Ferocia/karma-gzip/blob/master/lib/index.js#L9

and the plugin: https://github.com/Ferocia/karma-gzip/blob/master/lib/Plugin.js#L61-L71

Same thing actually as Browserify.

**Comment by TrySound** [comment]
Yeah, but please don't split $inject and function itself. It's aweful.

**Comment by ghost** [comment]
ok. Anyway. I think we have a solution? Study this code

https://github.com/Chialab/karma-systemjs-preprocessor/blob/master/lib/systemjs.js#L55-L76

**Comment by ghost** [comment]
My time is up, but I also found that all files is hooked on the window. So you can grab the files like this:
window.**karma**.files

Better example here:  https://github.com/tamtakoe/karma-requirejs-preprocessor/blob/master/index.js#L46-L51

Also this `window.__karma__.start` used as callback.

**Comment by brianmhunt** [comment]
Incidentally, my SO question has a few comments I made on this, at http://stackoverflow.com/questions/37795680

Whatever mechanisms are available appear to be a poorly documented part of the Karma API.  It's a bit of a relief that it's such a pain ... it's not just me. :smile:

**Comment by ghost** [comment]
Agree this is a PITA. But hopefully it will be solved soon. My next step
will be to read the whole karma source code.

**Comment by ghost** [comment]
@TrySound  I looked at the karma source. A mess. But they are using event emmiters. Old code. Probably  promises can be used.
Just now I'm tempted to develop my own solution Ala karma. We will see what I do tomorrow if this can't be fixed.  So far I can do basic stuff from cli .  Yep. I started on it...

**Comment by ghost** [comment]
@TrySound Did you look into this? I will not be online the next days, working on analyzing Karma source code etc. As far as I see now, there is no easy solution.  But an emitter would probably solve this, and most of Karma code seems only to invoke code directly from plugin, frameworks etc.

I will come back to this soon as I know exactly whats going on here.

**Comment by TrySound** [comment]
Not yet. Will look this night.

**Comment by ghost** [comment]
ok. I think it will be little hard to fix. Somehow you will need an
emitter, and check if files have changed, and restart Karma. And if you
look at this $inject, it's part of this NPM module ( 3 years ld).
https://www.npmjs.com/package/di
I'm in the middle of preprocessing now locale so I will know it soon.
Started to develop my own Karma look-a-like solution. CLI is fixed, and
config.

**Comment by ghost** [comment]
@TrySound All I can say is this is tricky, and related to the HTTP server Karma are using, and Karma's own middleware. And for me now it seems like the preprocessor is more or less static. It takes the files and do some magic on them and send them back. However. The watch task uses a more complicated algorithm.

And everything is a module in Karma, and every module get injected when the server get invoked. So a preprocessor is outer layer on top of the internal code. So far I can't see how this can be done without fixing something in the Karma core to get it correct. 

Dirty hacks I guess is possible... Karma's middleware inject variabels in the global scope - e.g. __KARMA_FILES_ to keep track on the files in an array. 

And you can start and stop Karma if you invoke this callbacks too. So maybe just listen for file changes, and trigger an restart of Karma if any changes?

I'm still investigating...

**Comment by TrySound** [comment]
But karma restart will also will restart server. It could be very expensive. Or it is happend every time?

**Comment by ghost** [comment]
I have no good answer except I know what's causing this. In karma you have
a watch task. This files is stored in a container on the window it seems.
__karma__files. Issue seem to occour with di and lodash dependency.

So if you somehow can get the files from there?

**Comment by ghost** [comment]
@TrySound  I will know more soon, but the files is first served by the server. Then they are hooked on the window object like this:  `'window.__karma__.files = {\n' + mappings.join(',\n') + '\n};\n';`
The watch task uses this files.

Seems to be complicated, and bad documentation and API.

**Comment by TrySound** [comment]
@Kflash Bad? It doesn't exist :))

**Comment by ghost** [comment]
I know. That's the reason why I'm developing my own task runner now where I actually solve this issues.

**Comment by ghost** [comment]
@TrySound I'm getting closer to an solution ....

``` js
13 07 2016 14:08:03.500:INFO [Jeibo]: |---- Launching the server with Jeibo at http://localhost:9876/---|
13 07 2016 14:08:03.503:INFO [launcher]: You are using Chrome browser.
```

**Comment by ghost** [comment]
@TrySound here is how it works.... in the configuration file you set the files to run test on. Webserver starts and save the files in an array on the window object. When you run tests the browser open on a specific port with unique Id. You see it in the browser url. This html  file is named static.html. 

On a watch task the browser window stay open and the server listen on the port. If any changes with the files a karma.js file get invoked and trigger the Webserver  very to restart and updated files in the array.

I don't think this helped too much. .. and the files are sent to the preprocessor before mocha or jasmine get them

**Comment by ghost** [comment]
@TrySound Karma 1.x have a new option -  `this.restartOnFileChange = false`. Set to false by default.

**Comment by TrySound** [comment]
Nice

**Comment by ghost** [comment]
@TrySound I'm done with Karma for now, and focusing on developing an Karma alternative. 
Everything is here: https://github.com/jeibo/jeibo

Basic setup for now, but I'm pushing online as soon as I have done something. This is just a slooow project. I can send you a invite there later on.

**Comment by ghost** [comment]
@TrySound seems like the issue is related karma.

**Comment by ghost** [comment]
@TrySound I guess this isn't a case anymore. So closing. Re-open if you got a fix.
