### ISSUE TITLE
Include directly from repository via npm/package.json

### ISSUE THREAD

**Issue by brianmhunt** [Kflash/karma-rollup-plugin#15]
If one adds `"karma-rollup-plugin": "Kflash/karma-rollup-plugin"` to `dependencies` or `devDependencies` of `package.json` and runs `npm install` then node will fail with a "Cannot find plugin".

This is because `package.json` has `"main": "dist/rollup-plugin-karma.js"`, but that is not present when `npm install` gets the package from Github.

There are a few options to resolve this e.g.
1. keep a `dist/` directory on master.
2. add git tags  releases/branches (and then `package.json` can reference that tagged version)
3. include `rollup.config.js` in `files` of `package.json` (so it can be at least compiled without having to explicitly fetch it)

There may be other/better ways to resolve this, but I just thought I'd give a heads up since `npm` supports installation from repository, and it's probably the easiest way to try out and debug the latest.

Cheers.

**Comment by ghost** [comment]
@brianmhunt I had identical issues yesterday. Could you push a PR? 
I'm in the middle of developing a new Karma + Rollup testrunner from scratch.  It will work like Karma, but the source and the AST is more or less how you use Rollup.

@TrySound Could you look into it?

**Comment by TrySound** [comment]
@Kflash I thought you can't fetch `dist` from npm. I don't beleive this is necessary repo uglifying. For dev process you are always able to copy paste dist. Or at least run `npm install` by hands in node_modules

**Comment by brianmhunt** [comment]
The `dist/` directory is included or excluded depending on the `files` in `package.json` or inclusion in `.npmignore`, respectively.  IIRC there are no special rules for `dist/`.

It is usual and useful to include either the latest tagged distribution or compiled HEAD in the npm's `dist/`, but `npm install` should not be a huge bother for folks who are going through the trouble of referencing the repo directly from `package.json`.

**Comment by TrySound** [comment]
What the people will reference the repo directly? It doesn't make sense except dev process.

**Comment by brianmhunt** [comment]
One can only speculate on all reasons, but the npm folks thought it worthwhile to provide as an option.  I have used it to get the HEAD version and modify it to try out new things as a dependency of an existing project.

It basically makes it unnecessary to clone the project from Github and then symlink it from the `node_modules/`.  Which can be handy, I have to admit, particularly for fast moving projects that are relied upon by multiple dependant projects and one wants to try them all out.

But it's all good, one way or the other. :smile:

**Comment by ghost** [comment]
@brianmhunt @TrySound seems like I'm late to the discussion here, but did you two come to a conclusion?

**Comment by brianmhunt** [comment]
Would it make sense to just include the `rollup.conf.js` in the `package.json` `files` section?

**Comment by ghost** [comment]
@brianmhunt Maybe. I will give it a try, and you test it and report back. Ok?

**Comment by brianmhunt** [comment]
Ok

**Comment by ghost** [comment]
I guess this one is fixed. So closing
