### ISSUE TITLE
no time to maintenance

### ISSUE THREAD

**Issue by ghost** [Kflash/karma-rollup-plugin#31]
@TrySound I have no time anymore to maintain this repo because I'm working on a huge project, and things are not completed yet. Should I transfer it to you? If not I think it will be deleted shortly.

**Comment by TrySound** [comment]
Yep. You can transfer.

**Comment by ghost** [comment]
Ok. I will transfer shortly. If you want a insight in what Jeibo has become, let me know and I can send a link. 

Now I'm done with this repo :)

**Comment by ghost** [comment]
@TrySound I had a GIT breakdown and lost a lot of data etc. Upon restore you vanished from candeza. Can you accept again? Still rebuilding stuff :(

**Comment by TrySound** [comment]
@Kflash Can you give me npm permissions?

**Comment by ghost** [comment]
I will try to fix within a few hours. Midnight here

**Comment by ghost** [comment]
Seems like I can't? Any idea how?

**Comment by TrySound** [comment]
There's a plus icon near your photo in package page
https://www.npmjs.com/package/karma-rollup-plugin
Don't forget to login.

**Comment by ghost** [comment]
I know, but the issue is that when I login there is no plus sign and the
package isn't registered on me. I have no idea how  NPM screwed this up

**Comment by TrySound** [comment]
@Kflash Are you sure you use the same login?
https://www.npmjs.com/~kflash123

**Comment by TrySound** [comment]
@Kflash So it's dead?

**Comment by ghost** [comment]
I dont know what is dead here but you have had npm access last 6 days

**Comment by TrySound** [comment]
Nice! Didn't got notification.

**Comment by ghost** [comment]
Sounds spooky. Check npm. You should see yourself

**Comment by TrySound** [comment]
@Kflash Yeah, I have now. Didn't know. npm doesn't have notification.
