### ISSUE TITLE
Redundant console.log published

### ISSUE THREAD

**Issue by borodean** [Kflash/karma-rollup-plugin#34]
Version 0.23, line 46 of dist/rollup-plugin-karma.js has this:

``` js
console.log(files);
```

Since I don't see this in the repo, I guess something wrong was published.

**Comment by borodean** [comment]
The dist file distributed by npm differs from the one that may be generated from the source code: https://www.diffchecker.com/lbm9NXGt

**Comment by weizhenye** [comment]
``` js
bundle.modules.forEach(function (module) {      
  files.unshift(createPattern(module.id));      
});
```

This code may the reason cause files loaded before frameworks.
See [this build result](https://travis-ci.org/weizhenye/Danmaku/builds/159088711), the preprocessed file `test.js` is loaded before mocha and chai, which results `Uncaught ReferenceError: describe is not defined`.

Please publish a new release which is generated from the source code. And add some hooks like `prepublish` to package.json may helpful to avoid accidental fault.

**Comment by TrySound** [comment]
Done. Sorry for delay.
