### ISSUE TITLE
Prefer buble to babel

### ISSUE THREAD

**Issue by TrySound** [Kflash/karma-rollup-plugin#5]
There is `buble/register` hook. This will make tests a bit more consistent to source code.

``` js
// You don't need to specify exact path. `package.json` `main` field will be resolved perfectly.
const karmaRollupPlugin = require('../../');
```

**Comment by ghost** [comment]
I will look into it soon. Need to run out. BTW.  I give you access rights
to this repo

**Comment by TrySound** [comment]
Thanks!:)

**Comment by ghost** [comment]
@TrySound How are you thinking here? Buble have no support for import statements. So your suggestion is to rewrite the tests to use require, and get rid of Babel?

**Comment by TrySound** [comment]
Yep. I don't see the problem here. You don't use modules in src

**Comment by ghost** [comment]
Ok. Will fix it soon.

**Comment by ghost** [comment]
@TrySound Babel is now gone. Need to clean it up later. No more time atm. Regarding your other issue, could you take a look at it?

Close this?
