### ISSUE TITLE
The debounce needs to be factored out

### ISSUE THREAD

**Issue by brianmhunt** [Kflash/karma-rollup-plugin#6]
The debounce on line 45 is creating a new debounced' function for every dependency of every processed file. This exponentially increases the computational complexity.

The debounce'd function definition should be moved outside the `createPreprocessor` function. e.g.

``` javascript
let triggerUpdateChanges = debounce(() => {
                                    let now = new Date();
                                    for (let idx = 0, lst = changedParents.values(); idx < lst.length; idx += 1) {
                                        fs.utimes(lst[idx], now, now);
                                    }
                                    changedParents.clear();
                                }, WAIT)
```

Then line 45 would just be `triggerUpdateChanges()`.

**Comment by ghost** [comment]
I see the issue. Could you send a pr on it? Not home atm. If not I will fix
it when I'm home

**Comment by ghost** [comment]
@brianmhunt I just arrived home. Will push a fix within 5 minutes, and credit you for this.

**Comment by ghost** [comment]
I close this now.

**Comment by ghost** [comment]
@brianmhunt This breaks nodeJS 0.12, Any idea for an solution? Solved!

**Comment by brianmhunt** [comment]
:thumbs_up: :)

**Comment by ghost** [comment]
@brianmhunt Your implementation seems to be a little buggy. Could you look into it?

See this issue: https://github.com/Kflash/karma-rollup-plugin/issues/14
